CREATE VIEW LUG_LOST AS
SELECT id_luggage,PASSENGER_id_passenger
FROM LUGGAGE
WHERE flight_status=FALSE;

CREATE VIEW PAS_LOST AS
SELECT id_passenger
FROM PASSENGER
WHERE flight_status=FALSE;

CREATE VIEW PAS_LUG_LOST AS
SELECT id_luggage,PASSENGER_id_passenger
FROM LUG_LOST
JOIN PAS_LOST
ON LUG_LOST.PASSENGER_id_passenger=PAS_LOST.id_passenger;

CREATE VIEW UNION_LOST AS
SELECT id_luggage FROM PAS_LUG_LOST
UNION 
SELECT id_luggage FROM LUG_LOST;

SELECT COUNT(id_luggage)
FROM UNION_LOST
